NIFTY_50 = [
    "RELIANCE", "TCS", "HDFCBANK", "ICICIBANK", "BHARTIARTL",
    "INFY", "ITC", "HINDUNILVR", "LT", "SBIN",
    "BAJFINANCE", "KOTAKBANK", "AXISBANK", "M&M", "MARUTI",
    "ASIANPAINT", "SUNPHARMA", "TITAN", "ULTRACEMCO", "TATASTEEL",
    "NTPC", "TATAMOTORS", "POWERGRID", "BAJAJFINSV", "NESTLEIND",
    "ADANIENT", "HCLTECH", "ONGC", "WIPRO", "JSWSTEEL",
    "ADANIPORTS", "HDFCLIFE", "LTIM", "SBILIFE", "COALINDIA",
    "TATACONSUM", "GRASIM", "BRITANNIA", "BAJAJ-AUTO", "EICHERMOT",
    "APOLLOHOSP", "DRREDDY", "HINDALCO", "CIPLA", "INDUSINDBK",
    "DIVISLAB", "TECHM", "HEROMOTOCO", "UPL", "BPCL"
]
